volumes:
    postgres-data:
        external: true
    pg-admin:
        external: true

services:
    postgres:
        image: postgres:16.1-bullseye
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
            POSTGRES_DB: nlb-db
        ports:
            - 15432:5432

    fastapi:
        environment:
            CORS_HOST: http://localhost:5173
            DATABASE_URL: postgresql://user:password@postgres/nlb-db
            PORT: 8000
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./api:/app

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./ghi:/app
        ports:
            - "5173:5173"
        environment:
            - VITE_API_HOST=$VITE_API_HOST

    pg-admin:
        image: dpage/pgadmin4
        volumes:
            - pg-admin:/var/lib/pgadmin
        ports:
            - 8082:80
        environment:
            PGADMIN_DEFAULT_EMAIL: user@email.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_DISABLE_POSTFIX: 1
